name: InfiniteBuckets
main: com.pluginsell.infiniteBuckets.Main
version: 1.8
authors: [EggZackley]
description: Infinite Lava Buckets and Infinite Water Buckets
website: https://discord.gg/w7ZGPXGpaX
commands:
  infinitebuckets:
    aliases:
      - infinitebucket
      - infiniteb
      - infbuckets
      - infbucket
      - infb
      - ib
      - ibucket
      - ibuckets
    usage: /<command>